# -*- coding: utf-8 -*-
"""upload

Automatically generated by Colab.

Upload tuned model to hugging face

install hugging face
"""

pip install huggingface_hub

"""import and login(log in with hugging face token with write permission)"""

from huggingface_hub import notebook_login

notebook_login()

"""connect to google drive"""

from google.colab import drive

drive.mount('/mount')

"""import model and tokenizer"""

from transformers import AutoModelForSequenceClassification, AutoTokenizer

directory_path = "PATH_TO_DIRECTORY"
model = AutoModelForSequenceClassification.from_pretrained(directory_path)
tokenizer = AutoTokenizer.from_pretrained(directory_path)

"""upload"""

repo_name = "USERNAME/REPOSITORY_NAME"
tokenizer.push_to_hub(repo_name)
model.push_to_hub(repo_name)
